name: 14
timestamp: 1653194172
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1651560790
positions:
  header-search: 'Module Position'
  navigation-button: 'Module Position'
  position-6650: Position-6650
  breadcrumbs: Breadcrumbs
  position-8049: Position-8049
  footer: 'Module Position'
sections:
  topbar: Topbar
  navigation: Navigation
  pagetitle: Pagetitle
  sidebar: Sidebar
  copyright: Copyright
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  social:
    social-8812: Social
    social-6649: Social
    social-9176: Social
  logo:
    logo-5836: 'Logo / Image'
  position:
    position-position-3473: 'Module Position'
    position-position-2908: 'Module Position'
    position-position-6650: Position-6650
    position-breadcrumbs: Breadcrumbs
    position-position-8049: Position-8049
    position-position-6269: 'Module Position'
  menu:
    menu-9266: Menu
  messages:
    system-messages-5477: 'System Messages'
  content:
    system-content-1161: 'Page Content'
  copyright:
    copyright-4571: Copyright
  mobile-menu:
    mobile-menu-2000: Mobile-menu
inherit: {  }
