name: 20
timestamp: 1664874300
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: quix
  timestamp: 1651560790
positions:
  topbar-right: 'Language switcher'
  footer: 'Module Position'
sections:
  topbar: Topbar
  navigation: Navigation
  contentbottom: Contentbottom
  copyright: Copyright
  header: Header
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  social:
    social-9071: Social
    social-8812: Social
    social-9176: Social
  logo:
    logo-5836: 'Logo / Image'
  menu:
    menu-9266: Menu
    menu-5313: Menu
  position:
    position-position-1937: 'Language switcher'
    position-position-6269: 'Module Position'
  messages:
    system-messages-5477: 'System Messages'
  content:
    system-content-1161: 'Page Content'
  copyright:
    copyright-4571: Copyright
  mobile-menu:
    mobile-menu-8586: Mobile-menu
inherit: {  }
